name: ecofier
description: Make your room eco-friendly with Ecofier.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  logger: ^2.3.0
  camera: ^0.11.0+1
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true