name: ecofier
description: Make your room eco-friendly with Ecofier.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  cupertino_icons: ^1.0.8
  logger: ^2.3.0
  camera: ^0.11.0+1
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 600
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 800
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 900